/* tigress complex.c --Transform=Virtualize --Functions=isValidLicenseKey --out=insane.c */
/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

union _1_isValidLicenseKey_$node;
struct _IO_FILE;
struct timeval;
enum _1_isValidLicenseKey_$op;
extern void exit(int status ) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
extern int fclose(void *stream ) ;
extern int close(int filedes ) ;
extern int puts(char const   *__s ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
char **_global_argv  =    (char **)0;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int unlink(char const   *filename ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
union _1_isValidLicenseKey_$node {
   void *_void_star ;
   unsigned long long _unsigned_long_long ;
   long long _long_long ;
   unsigned long _unsigned_long ;
   long _long ;
   unsigned short _unsigned_short ;
   short _short ;
   unsigned int _unsigned_int ;
   int _int ;
   unsigned char _unsigned_char ;
   signed char _signed_char ;
   char _char ;
};
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern int raise(int sig ) ;
extern void abort() ;
extern int atoi(char const   *s ) ;
int isValidLicenseKey(char const   *input ) ;
extern void *malloc(unsigned long size ) ;
extern int getpagesize() ;
extern int posix_memalign(void **memptr , unsigned long alignment , unsigned long size ) ;
extern int pthread_join(void *thread , void **value_ptr ) ;
extern int rand() ;
extern void free(void *ptr ) ;
extern unsigned long strlen(char const   *s ) ;
int main(int argc , char **argv , char **_formal_envp ) ;
extern int write(int filedes , void *buf , int nbyte ) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
int _global_argc  =    0;
void megaInit(void) ;
char **_global_envp  =    (char **)0;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern int printf(char const   * __restrict  __format  , ...) ;
extern int scanf(char const   *format  , ...) ;
extern void perror(char const   *str ) ;
extern long clock(void) ;
extern int read(int filedes , void *buf , int nbyte ) ;
extern int gethostname(char *name , unsigned long namelen  , ...) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern void qsort(void *base , unsigned long nel , unsigned long width , int (*compar)(void *a ,
                                                                                       void *b ) ) ;
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern int strcmp(char const   *a , char const   *b ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern void signal(int sig , void *func ) ;
extern long time(long *tloc ) ;
typedef struct _IO_FILE FILE;
enum _1_isValidLicenseKey_$op {
    _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 35,
    _1_isValidLicenseKey__goto$label_LAB_0 = 217,
    _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0 = 36,
    _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1 = 20,
    _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0 = 82,
    _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0 = 111,
    _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0 = 19,
    _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1 = 226,
    _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0 = 193,
    _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0 = 95,
    _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0 = 21,
    _1_isValidLicenseKey__load_int$left_STA_0$result_STA_0 = 61,
    _1_isValidLicenseKey__local$result_STA_0$value_LIT_0 = 203,
    _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0 = 40,
    _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1 = 146,
    _1_isValidLicenseKey__return_int$expr_STA_0 = 181
} ;
unsigned char _1_isValidLicenseKey_$array[1][1015]  = { {        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)86,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,
            _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,        _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,
            (unsigned char)9,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)182,        (unsigned char)3,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)97,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,
            _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,
            (unsigned char)120,        (unsigned char)3,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)108,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,
            (unsigned char)2,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,
            _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,        _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,
            (unsigned char)9,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)58,        (unsigned char)3,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)105,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)3,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,
            _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,
            (unsigned char)252,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)100,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,
            _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,        _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,
            (unsigned char)9,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)190,        (unsigned char)2,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)76,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)5,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,
            _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,
            (unsigned char)128,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)105,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,
            (unsigned char)6,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,
            _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,        _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,
            (unsigned char)9,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)66,        (unsigned char)2,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)99,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)7,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,
            _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,
            (unsigned char)4,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)101,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,
            _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,        _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,
            (unsigned char)9,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)198,        (unsigned char)1,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)110,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)9,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,
            _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,
            (unsigned char)136,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)115,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,
            (unsigned char)10,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,
            _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,        _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,
            (unsigned char)9,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)74,        (unsigned char)1,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)101,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)11,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,
            _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,
            (unsigned char)12,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)75,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,
            (unsigned char)12,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,
            _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,        _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,
            (unsigned char)9,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)206,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)101,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)13,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,
            _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,
            (unsigned char)144,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)121,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,
            (unsigned char)14,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,
            _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,        _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,
            (unsigned char)9,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,
            _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)82,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)15,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0,
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0,        _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0,
            _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)25,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,        _1_isValidLicenseKey__goto$label_LAB_0,        (unsigned char)4,
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__goto$label_LAB_0,
            (unsigned char)20,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,
            (unsigned char)0,        (unsigned char)0,        _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1,        _1_isValidLicenseKey__goto$label_LAB_0,
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0,
            _1_isValidLicenseKey__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0,
            (unsigned char)0,        _1_isValidLicenseKey__load_int$left_STA_0$result_STA_0,        _1_isValidLicenseKey__return_int$expr_STA_0}};
extern int fprintf(struct _IO_FILE *stream ,
                   char const   *format  , ...) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern double sqrt(double x ) ;
char const   *_1_isValidLicenseKey_$strings  =    "";
extern double log(double x ) ;
extern int snprintf(char *str , unsigned long size , char const   *format  , ...) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned long size ) ;
void megaInit(void)
{


  {

}
}
int main(int argc , char **argv , char **_formal_envp )
{
  int tmp ;
  int _BARRIER_0 ;

  {
  megaInit();
  _global_argc = argc;
  _global_argv = argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  if (argc != 2) {
    puts("Please provide your license key as an argument!");
    return (-1);
  }
  tmp = isValidLicenseKey((char const   *)*(argv + 1));
  if (tmp) {
    puts("This license is valid!");
  } else {
    puts("Nope ...");
    return (1);
  }
  return (0);
}
}
int isValidLicenseKey(char const   *input )
{
  char _1_isValidLicenseKey_$locals[12] ;
  union _1_isValidLicenseKey_$node _1_isValidLicenseKey_$stack[1][32] ;
  union _1_isValidLicenseKey_$node *_1_isValidLicenseKey_$sp[1] ;
  unsigned char *_1_isValidLicenseKey_$pc[1] ;

  {
  _1_isValidLicenseKey_$sp[0] = _1_isValidLicenseKey_$stack[0];
  _1_isValidLicenseKey_$pc[0] = _1_isValidLicenseKey_$array[0];
  while (1) {
    switch (*(_1_isValidLicenseKey_$pc[0])) {
    case _1_isValidLicenseKey__load_void_star$left_STA_0$result_STA_0:
    (_1_isValidLicenseKey_$pc[0]) ++;
    (_1_isValidLicenseKey_$sp[0] + 0)->_void_star = *((void **)(_1_isValidLicenseKey_$sp[0] + 0)->_void_star);
    break;
    case _1_isValidLicenseKey__load_char$left_STA_0$result_STA_0:
    (_1_isValidLicenseKey_$pc[0]) ++;
    (_1_isValidLicenseKey_$sp[0] + 0)->_char = *((char *)(_1_isValidLicenseKey_$sp[0] + 0)->_void_star);
    break;
    case _1_isValidLicenseKey__goto$label_LAB_0:
    (_1_isValidLicenseKey_$pc[0]) ++;
    _1_isValidLicenseKey_$pc[0] += *((int *)_1_isValidLicenseKey_$pc[0]);
    break;
    case _1_isValidLicenseKey__convert_int2unsigned_long$left_STA_0$result_STA_0:
    (_1_isValidLicenseKey_$pc[0]) ++;
    (_1_isValidLicenseKey_$sp[0] + 0)->_unsigned_long = (unsigned long )(_1_isValidLicenseKey_$sp[0] + 0)->_int;
    break;
    case _1_isValidLicenseKey__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1:
    (_1_isValidLicenseKey_$pc[0]) ++;
    (_1_isValidLicenseKey_$sp[0] + -1)->_void_star = (_1_isValidLicenseKey_$sp[0] + -1)->_void_star + (_1_isValidLicenseKey_$sp[0] + 0)->_unsigned_long;
    (_1_isValidLicenseKey_$sp[0]) --;
    break;
    case _1_isValidLicenseKey__convert_char2int$left_STA_0$result_STA_0:
    (_1_isValidLicenseKey_$pc[0]) ++;
    (_1_isValidLicenseKey_$sp[0] + 0)->_int = (int )(_1_isValidLicenseKey_$sp[0] + 0)->_char;
    break;
    case _1_isValidLicenseKey__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1:
    (_1_isValidLicenseKey_$pc[0]) ++;
    (_1_isValidLicenseKey_$sp[0] + -1)->_unsigned_long = (_1_isValidLicenseKey_$sp[0] + -1)->_unsigned_long * (_1_isValidLicenseKey_$sp[0] + 0)->_unsigned_long;
    (_1_isValidLicenseKey_$sp[0]) --;
    break;
    case _1_isValidLicenseKey__local$result_STA_0$value_LIT_0:
    (_1_isValidLicenseKey_$pc[0]) ++;
    (_1_isValidLicenseKey_$sp[0] + 1)->_void_star = (void *)(_1_isValidLicenseKey_$locals + *((int *)_1_isValidLicenseKey_$pc[0]));
    (_1_isValidLicenseKey_$sp[0]) ++;
    _1_isValidLicenseKey_$pc[0] += 4;
    break;
    case _1_isValidLicenseKey__formal$result_STA_0$value_LIT_0:
    (_1_isValidLicenseKey_$pc[0]) ++;
    switch (*((int *)_1_isValidLicenseKey_$pc[0])) {
    case 0:
    (_1_isValidLicenseKey_$sp[0] + 1)->_void_star = (void *)(& input);
    break;
    }
    (_1_isValidLicenseKey_$sp[0]) ++;
    _1_isValidLicenseKey_$pc[0] += 4;
    break;
    case _1_isValidLicenseKey__Ne_int_int2int$left_STA_0$result_STA_0$right_STA_1:
    (_1_isValidLicenseKey_$pc[0]) ++;
    (_1_isValidLicenseKey_$sp[0] + -1)->_int = (_1_isValidLicenseKey_$sp[0] + 0)->_int != (_1_isValidLicenseKey_$sp[0] + -1)->_int;
    (_1_isValidLicenseKey_$sp[0]) --;
    break;
    case _1_isValidLicenseKey__constant_unsigned_long$result_STA_0$value_LIT_0:
    (_1_isValidLicenseKey_$pc[0]) ++;
    (_1_isValidLicenseKey_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_1_isValidLicenseKey_$pc[0]);
    (_1_isValidLicenseKey_$sp[0]) ++;
    _1_isValidLicenseKey_$pc[0] += 8;
    break;
    case _1_isValidLicenseKey__store_int$right_STA_0$left_STA_1:
    (_1_isValidLicenseKey_$pc[0]) ++;
    *((int *)(_1_isValidLicenseKey_$sp[0] + -1)->_void_star) = (_1_isValidLicenseKey_$sp[0] + 0)->_int;
    _1_isValidLicenseKey_$sp[0] += -2;
    break;
    case _1_isValidLicenseKey__return_int$expr_STA_0:
    (_1_isValidLicenseKey_$pc[0]) ++;
    return ((_1_isValidLicenseKey_$sp[0] + 0)->_int);
    break;
    case _1_isValidLicenseKey__constant_int$result_STA_0$value_LIT_0:
    (_1_isValidLicenseKey_$pc[0]) ++;
    (_1_isValidLicenseKey_$sp[0] + 1)->_int = *((int *)_1_isValidLicenseKey_$pc[0]);
    (_1_isValidLicenseKey_$sp[0]) ++;
    _1_isValidLicenseKey_$pc[0] += 4;
    break;
    case _1_isValidLicenseKey__load_int$left_STA_0$result_STA_0:
    (_1_isValidLicenseKey_$pc[0]) ++;
    (_1_isValidLicenseKey_$sp[0] + 0)->_int = *((int *)(_1_isValidLicenseKey_$sp[0] + 0)->_void_star);
    break;
    case _1_isValidLicenseKey__branchIfTrue$expr_STA_0$label_LAB_0:
    (_1_isValidLicenseKey_$pc[0]) ++;
    if ((_1_isValidLicenseKey_$sp[0] + 0)->_int) {
      _1_isValidLicenseKey_$pc[0] += *((int *)_1_isValidLicenseKey_$pc[0]);
    } else {
      _1_isValidLicenseKey_$pc[0] += 4;
    }
    (_1_isValidLicenseKey_$sp[0]) --;
    break;
    }
  }
}
}
